### ISSUE TITLE
The content will be forcibly formatted

### ISSUE THREAD

**Issue by Liuruyong** [mohakapt/Stringz#10]
The content will be forcibly formatted, especially comments. Added a string, modified a lot of content.

**Comment by mohakapt** [comment]
I'm aware of this issue, and I'm thinking about some kind of solution, due to how Stringz handles values it's not so easy to change only a portion of the file, so currently Stringz overrides the entire file. I will try to fix this issue but meanwhile you can check `Exporting` preferences It contains some options related to exporting format, Also keep in mind that Stringz only changes the format of the file the first time you edit it. After that the format stays the same so you might consider committing the new format to source control to avoid getting too much changes in your files.
